apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-sync
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vpa-reader
  namespace: default
rules:
- apiGroups: ["autoscaling.k8s.io"]
  resources: ["verticalpodautoscalers"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vpa-sync-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: vpa-sync
  namespace: default
roleRef:
  kind: Role
  name: vpa-reader
  apiGroup: rbac.authorization.k8s.io