apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-vpa-test-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd-test
  template:
    metadata:
      labels:
        app: argocd-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
