apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: default
spec:
  replicas: 10  # 10 load generators
  selector:
    matchLabels:
      app: load-gen
  template:
    metadata:
      labels:
        app: load-gen
    spec:
      containers:
      - name: load
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Each generator makes 2 requests per second
          while true; do 
            wget -q -O- http://metrics-app.default.svc.cluster.local/ > /dev/null 2>&1
            sleep 0.5
          done
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
