apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-app
  namespace: default
  labels:
    app: metrics-app
    release: prometheus  # Important: Match your Helm release name
spec:
  selector:
    matchLabels:
      app: metrics-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
