apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-wasteful-app
  labels:
    app: test-vpa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-vpa
  template:
    metadata:
      labels:
        app: test-vpa
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: RestartContainer
        resources:
          requests:
            cpu: 1000m      # Over-provisioned
            memory: 1Gi     # Over-provisioned
          limits:
            cpu: 2000m
            memory: 2Gi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-vpa-service
spec:
  selector:
    app: test-vpa
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
